# Table of Contents
 <p><div class="lev1 toc-item"><a href="#数据结构" data-toc-modified-id="数据结构-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>数据结构</a></div><div class="lev2 toc-item"><a href="#字典" data-toc-modified-id="字典-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>字典</a></div><div class="lev2 toc-item"><a href="#迭代器" data-toc-modified-id="迭代器-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>迭代器</a></div><div class="lev2 toc-item"><a href="#列表" data-toc-modified-id="列表-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>列表</a></div><div class="lev3 toc-item"><a href="#append-&amp;-extend" data-toc-modified-id="append-&amp;-extend-131"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>append &amp; extend</a></div><div class="lev3 toc-item"><a href="#remove" data-toc-modified-id="remove-132"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>remove</a></div><div class="lev3 toc-item"><a href="#pop" data-toc-modified-id="pop-133"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>pop</a></div><div class="lev2 toc-item"><a href="#元组" data-toc-modified-id="元组-14"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>元组</a></div><div class="lev2 toc-item"><a href="#切片" data-toc-modified-id="切片-15"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>切片</a></div><div class="lev2 toc-item"><a href="#set" data-toc-modified-id="set-16"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>set</a></div><div class="lev1 toc-item"><a href="#迭代器" data-toc-modified-id="迭代器-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>迭代器</a></div><div class="lev2 toc-item"><a href="#map" data-toc-modified-id="map-21"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>map</a></div><div class="lev2 toc-item"><a href="#匿名函数--lambda" data-toc-modified-id="匿名函数--lambda-22"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>匿名函数  lambda</a></div><div class="lev2 toc-item"><a href="#reduce（累积）" data-toc-modified-id="reduce（累积）-23"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>reduce（累积）</a></div><div class="lev2 toc-item"><a href="#filter" data-toc-modified-id="filter-24"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>filter</a></div><div class="lev1 toc-item"><a href="#数据IO" data-toc-modified-id="数据IO-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>数据IO</a></div><div class="lev2 toc-item"><a href="#导入" data-toc-modified-id="导入-31"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>导入</a></div><div class="lev2 toc-item"><a href="#存储" data-toc-modified-id="存储-32"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>存储</a></div><div class="lev2 toc-item"><a href="#dataframe-&amp;-series" data-toc-modified-id="dataframe-&amp;-series-33"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>dataframe &amp; series</a></div><div class="lev3 toc-item"><a href="#选取行" data-toc-modified-id="选取行-331"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>选取行</a></div><div class="lev3 toc-item"><a href="#选取列" data-toc-modified-id="选取列-332"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>选取列</a></div><div class="lev3 toc-item"><a href="#rename" data-toc-modified-id="rename-333"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span>rename</a></div><div class="lev3 toc-item"><a href="#drop_duplicates" data-toc-modified-id="drop_duplicates-334"><span class="toc-item-num">3.3.4&nbsp;&nbsp;</span>drop_duplicates</a></div><div class="lev3 toc-item"><a href="#value_counts" data-toc-modified-id="value_counts-335"><span class="toc-item-num">3.3.5&nbsp;&nbsp;</span>value_counts</a></div><div class="lev3 toc-item"><a href="#新建列" data-toc-modified-id="新建列-336"><span class="toc-item-num">3.3.6&nbsp;&nbsp;</span>新建列</a></div><div class="lev3 toc-item"><a href="#列操作" data-toc-modified-id="列操作-337"><span class="toc-item-num">3.3.7&nbsp;&nbsp;</span>列操作</a></div><div class="lev1 toc-item"><a href="#数据框操作" data-toc-modified-id="数据框操作-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>数据框操作</a></div><div class="lev2 toc-item"><a href="#series" data-toc-modified-id="series-41"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>series</a></div><div class="lev2 toc-item"><a href="#DataFrame" data-toc-modified-id="DataFrame-42"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>DataFrame</a></div><div class="lev2 toc-item"><a href="#pd.DataFrame.from_dict" data-toc-modified-id="pd.DataFrame.from_dict-43"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>pd.DataFrame.from_dict</a></div><div class="lev2 toc-item"><a href="#索引" data-toc-modified-id="索引-44"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>索引</a></div><div class="lev3 toc-item"><a href="#通过索引名称选取多行" data-toc-modified-id="通过索引名称选取多行-441"><span class="toc-item-num">4.4.1&nbsp;&nbsp;</span>通过索引名称选取多行</a></div><div class="lev3 toc-item"><a href="#指定行列，选择一个区域" data-toc-modified-id="指定行列，选择一个区域-442"><span class="toc-item-num">4.4.2&nbsp;&nbsp;</span>指定行列，选择一个区域</a></div><div class="lev3 toc-item"><a href="#数值型的统计数据" data-toc-modified-id="数值型的统计数据-443"><span class="toc-item-num">4.4.3&nbsp;&nbsp;</span>数值型的统计数据</a></div><div class="lev3 toc-item"><a href="#条件选取" data-toc-modified-id="条件选取-444"><span class="toc-item-num">4.4.4&nbsp;&nbsp;</span>条件选取</a></div><div class="lev3 toc-item"><a href="#iloc只接受索引位选取（行或列皆如此）" data-toc-modified-id="iloc只接受索引位选取（行或列皆如此）-445"><span class="toc-item-num">4.4.5&nbsp;&nbsp;</span>iloc只接受索引位选取（行或列皆如此）</a></div><div class="lev3 toc-item"><a href="#iloc不接受True／False，但loc接受" data-toc-modified-id="iloc不接受True／False，但loc接受-446"><span class="toc-item-num">4.4.6&nbsp;&nbsp;</span>iloc不接受True／False，但loc接受</a></div><div class="lev3 toc-item"><a href="#ix既可以接受名称，也可以接受位置" data-toc-modified-id="ix既可以接受名称，也可以接受位置-447"><span class="toc-item-num">4.4.7&nbsp;&nbsp;</span>ix既可以接受名称，也可以接受位置</a></div><div class="lev3 toc-item"><a href="#query（根据列条件来筛选）" data-toc-modified-id="query（根据列条件来筛选）-448"><span class="toc-item-num">4.4.8&nbsp;&nbsp;</span>query（根据列条件来筛选）</a></div><div class="lev2 toc-item"><a href="#多重索引" data-toc-modified-id="多重索引-45"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>多重索引</a></div><div class="lev3 toc-item"><a href="#set_index--&amp;--reset_index" data-toc-modified-id="set_index--&amp;--reset_index-451"><span class="toc-item-num">4.5.1&nbsp;&nbsp;</span>set_index  &amp;  reset_index</a></div><div class="lev3 toc-item"><a href="#条件切片选取先排序" data-toc-modified-id="条件切片选取先排序-452"><span class="toc-item-num">4.5.2&nbsp;&nbsp;</span>条件切片选取先排序</a></div><div class="lev3 toc-item"><a href="#slice" data-toc-modified-id="slice-453"><span class="toc-item-num">4.5.3&nbsp;&nbsp;</span>slice</a></div><div class="lev1 toc-item"><a href="#分组计算" data-toc-modified-id="分组计算-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>分组计算</a></div><div class="lev3 toc-item"><a href="#aggregate" data-toc-modified-id="aggregate-501"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>aggregate</a></div><div class="lev1 toc-item"><a href="#多表操作" data-toc-modified-id="多表操作-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>多表操作</a></div><div class="lev2 toc-item"><a href="#concat" data-toc-modified-id="concat-61"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>concat</a></div><div class="lev2 toc-item"><a href="#merge" data-toc-modified-id="merge-62"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>merge</a></div><div class="lev2 toc-item"><a href="#right_index" data-toc-modified-id="right_index-63"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>right_index</a></div><div class="lev1 toc-item"><a href="#内置函数(enumerate,zip)" data-toc-modified-id="内置函数(enumerate,zip)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>内置函数(enumerate,zip)</a></div><div class="lev2 toc-item"><a href="#enumerate" data-toc-modified-id="enumerate-71"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>enumerate</a></div><div class="lev2 toc-item"><a href="#zip" data-toc-modified-id="zip-72"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>zip</a></div><div class="lev1 toc-item"><a href="#数据透视表" data-toc-modified-id="数据透视表-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>数据透视表</a></div><div class="lev2 toc-item"><a href="#pivot_table" data-toc-modified-id="pivot_table-81"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>pivot_table</a></div><div class="lev2 toc-item"><a href="#crosstab" data-toc-modified-id="crosstab-82"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>crosstab</a></div><div class="lev1 toc-item"><a href="#numpy" data-toc-modified-id="numpy-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>numpy</a></div><div class="lev2 toc-item"><a href="#arange" data-toc-modified-id="arange-91"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>arange</a></div><div class="lev2 toc-item"><a href="#linspace" data-toc-modified-id="linspace-92"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>linspace</a></div><div class="lev2 toc-item"><a href="#np.ones" data-toc-modified-id="np.ones-93"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>np.ones</a></div><div class="lev2 toc-item"><a href="#np.eye" data-toc-modified-id="np.eye-94"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>np.eye</a></div><div class="lev2 toc-item"><a href="#np.zeros" data-toc-modified-id="np.zeros-95"><span class="toc-item-num">9.5&nbsp;&nbsp;</span>np.zeros</a></div><div class="lev2 toc-item"><a href="#random" data-toc-modified-id="random-96"><span class="toc-item-num">9.6&nbsp;&nbsp;</span>random</a></div><div class="lev2 toc-item"><a href="#concatenate" data-toc-modified-id="concatenate-97"><span class="toc-item-num">9.7&nbsp;&nbsp;</span>concatenate</a></div><div class="lev2 toc-item"><a href="#sum" data-toc-modified-id="sum-98"><span class="toc-item-num">9.8&nbsp;&nbsp;</span>sum</a></div><div class="lev2 toc-item"><a href="#numpy索引切片" data-toc-modified-id="numpy索引切片-99"><span class="toc-item-num">9.9&nbsp;&nbsp;</span>numpy索引切片</a></div><div class="lev2 toc-item"><a href="#花式索引" data-toc-modified-id="花式索引-910"><span class="toc-item-num">9.10&nbsp;&nbsp;</span>花式索引</a></div>

# 数据结构

## 字典

In [1]:
adir = {"name":"xiaoming","age":18,"gender":"male"}

In [2]:
adir['name']

'xiaoming'

In [3]:
adir.keys()

dict_keys(['name', 'age', 'gender'])

In [4]:
adir.items()

dict_items([('name', 'xiaoming'), ('age', 18), ('gender', 'male')])

In [5]:
for (k,v) in adir.items():
    print (k,v) 

name xiaoming
age 18
gender male


## 迭代器

In [6]:
for v in adir.values():
    print (v)

xiaoming
18
male


In [7]:
x = range(0,10)

In [8]:
x

range(0, 10)

In [9]:
for i in x:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [10]:
[j for j in x]  #生成器

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 列表

In [11]:
alist = [1,2,3,"xiaoming"]

### append & extend

In [12]:
alist.append(10)

In [13]:
alist

[1, 2, 3, 'xiaoming', 10]

In [14]:
blist = [5,6,7,8]

In [15]:
alist.append(blist)

In [16]:
alist

[1, 2, 3, 'xiaoming', 10, [5, 6, 7, 8]]

In [17]:
alist.extend(blist)

In [18]:
alist

[1, 2, 3, 'xiaoming', 10, [5, 6, 7, 8], 5, 6, 7, 8]

### remove

In [19]:
alist.remove('xiaoming')

In [20]:
alist

[1, 2, 3, 10, [5, 6, 7, 8], 5, 6, 7, 8]

### pop

In [21]:
alist.pop()

8

In [22]:
alist

[1, 2, 3, 10, [5, 6, 7, 8], 5, 6, 7]

## 元组

In [23]:
atuple = (1,2,3)     #不可修改

## 切片

In [24]:
alist

[1, 2, 3, 10, [5, 6, 7, 8], 5, 6, 7]

In [25]:
alist[1]

2

In [26]:
alist[2:4]

[3, 10]

## set

In [27]:
set([1,2,3,3,4,5,5,6])    #自动去重

{1, 2, 3, 4, 5, 6}

# 迭代器

## map

In [28]:
x = range(1,10)
a = [j for j in x]

In [29]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
def sum2(x):
    return x*2

In [31]:
[i for i in map(sum2,a)]

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
def sum22(x):
    return x*2,x*4

In [33]:
[j for j in map(sum22,a)]

[(2, 4),
 (4, 8),
 (6, 12),
 (8, 16),
 (10, 20),
 (12, 24),
 (14, 28),
 (16, 32),
 (18, 36)]

## 匿名函数  lambda

In [34]:
map(lambda x:x*2,a)

In [35]:
b = [i for i in map(lambda x :x*2,a)]
b

[2, 4, 6, 8, 10, 12, 14, 16, 18]

## reduce（累积）

In [36]:
from functools import reduce

In [37]:
reduce(lambda a,b:a+b,a)

45

In [38]:
reduce(lambda a,b:a*b,a)

362880

## filter

In [39]:
for i in filter(lambda s:s>5,a):
    print (i)

6
7
8
9


# 数据IO

In [5]:
import pandas as pd 

## 导入

In [6]:
df = pd.read_csv("forestfires.csv")

In [42]:
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

## 存储

In [43]:
df.to_csv("test1.csv",index = False)

## dataframe & series

In [44]:
type(df)

pandas.core.frame.DataFrame

In [45]:
df['X'].head()

0    7
1    7
2    7
3    8
4    8
Name: X, dtype: int64

In [46]:
type(df['X'])

pandas.core.series.Series

In [47]:
df.loc[0]

X           7
Y           5
month     mar
day       fri
FFMC     86.2
DMC      26.2
DC       94.3
ISI       5.1
temp      8.2
RH         51
wind      6.7
rain        0
area        0
Name: 0, dtype: object

In [48]:
type(df.loc[0])

pandas.core.series.Series

### 选取行

In [49]:
df[0:3]

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0

In [50]:
df[2:7]

X  Y month  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain  area
2  7  4   oct  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5  8  6   aug  sun  92.3  85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6  8  6   aug  mon  92.3  88.9  495.6   8.5  24.1  27   3.1   0.0   0.0

In [51]:
df[2:3]

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0

### 选取列

In [52]:
df[['X','Y']]

X  Y
0    7  5
1    7  4
2    7  4
3    8  6
4    8  6
5    8  6
6    8  6
7    8  6
8    8  6
9    7  5
10   7  5
11   7  5
12   6  5
13   6  5
14   6  5
15   6  5
16   5  5
17   8  5
18   6  4
19   6  4
20   6  4
21   5  4
22   7  4
23   7  4
24   7  4
25   7  4
26   7  4
27   7  4
28   6  3
29   6  3
..  .. ..
487  5  4
488  4  4
489  4  4
490  4  4
491  4  4
492  1  3
493  1  3
494  6  6
495  6  6
496  4  5
497  3  4
498  6  5
499  7  5
500  8  6
501  7  5
502  4  4
503  2  4
504  4  3
505  1  2
506  1  2
507  2  4
508  1  2
509  5  4
510  6  5
511  8  6
512  4  3
513  2  4
514  7  4
515  1  4
516  6  3

[517 rows x 2 columns]

In [53]:
df[['X','Y','area']][:5]

X  Y  area
0  7  5   0.0
1  7  4   0.0
2  7  4   0.0
3  8  6   0.0
4  8  6   0.0

In [54]:
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

### rename

In [55]:
df.rename(columns = {"X":"x","Y":"y"},inplace = True)

In [56]:
df.columns

Index(['x', 'y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')

In [57]:
df.shape

(517, 13)

### drop_duplicates

In [58]:
df1 = df.drop_duplicates(subset = ['month','day'])    #subset在哪些列上比对重复值，keep保留第几条

In [60]:
df1.shape

(64, 13)

In [61]:
df1.head()

x  y month  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
4  8  6   mar  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5  8  6   aug  sun  92.3  85.3  488.0  14.7  22.2  29   5.4   0.0   0.0

### value_counts

In [62]:
df['month'].value_counts()

aug    184
sep    172
mar     54
jul     32
feb     20
jun     17
oct     15
apr      9
dec      9
may      2
jan      2
nov      1
Name: month, dtype: int64

In [63]:
df['month'].value_counts().sum()

517

### 新建列

In [61]:
df['xx'] = df['x'] + df['x'] + df['y']

In [62]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  19
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  18
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  18
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  22
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  22

### 列操作

In [65]:
df['x'] * 10

0      70
1      70
2      70
3      80
4      80
5      80
6      80
7      80
8      80
9      70
10     70
11     70
12     60
13     60
14     60
15     60
16     50
17     80
18     60
19     60
20     60
21     50
22     70
23     70
24     70
25     70
26     70
27     70
28     60
29     60
       ..
487    50
488    40
489    40
490    40
491    40
492    10
493    10
494    60
495    60
496    40
497    30
498    60
499    70
500    80
501    70
502    40
503    20
504    40
505    10
506    10
507    20
508    10
509    50
510    60
511    80
512    40
513    20
514    70
515    10
516    60
Name: x, dtype: int64

# 数据框操作

In [66]:
alist = [1,2,3,4]

In [67]:
atuple= (1,2,3,4)

In [68]:
adir = {"name":"xiaoming","age":18,"sex":"male"}

## series

In [70]:
s1 = pd.Series(adir,name="test")

In [71]:
s1

age           18
name    xiaoming
sex         male
Name: test, dtype: object

In [74]:
list("abcd")

['a', 'b', 'c', 'd']

## DataFrame

In [75]:
pd.DataFrame(adir,index = list("abcd"))

age      name   sex
a   18  xiaoming  male
b   18  xiaoming  male
c   18  xiaoming  male
d   18  xiaoming  male

## pd.DataFrame.from_dict

In [82]:
pd.DataFrame.from_dict(adir,orient="index")

0
name  xiaoming
age         18
sex       male

In [89]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  19
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  18
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  18
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  22
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  22

## 索引

In [3]:
df[0:5]

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [84]:
df.loc[0:5]         #其实0:5取的是名称，loc是通过索引名称选取的

x  y month  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5  8  6   aug  sun  92.3  85.3  488.0  14.7  22.2  29   5.4   0.0   0.0

In [4]:
dfnew = df.set_index("month")

In [5]:
dfnew.head()

X  Y  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
month                                                               
mar    7  5  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
oct    7  4  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
oct    7  4  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
mar    8  6  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
mar    8  6  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [6]:
dfnew[0:5]   #是通过位置选取的

X  Y  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
month                                                               
mar    7  5  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
oct    7  4  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
oct    7  4  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
mar    8  6  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
mar    8  6  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

### 通过索引名称选取多行

In [7]:
dfnew.loc[["oct",'mar']]

X  Y  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain   area
month                                                                 
oct    7  4  tue  90.6  35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
oct    7  4  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
oct    8  5  mon  84.9  32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
oct    6  3  tue  90.6  35.4  669.1   6.7  21.7  24   4.5   0.0   0.00
oct    7  4  fri  90.0  41.5  682.6   8.7  11.3  60   5.4   0.0   0.00
oct    7  3  sat  90.6  43.7  686.9   6.7  17.8  27   4.0   0.0   0.00
oct    4  3  sun  92.6  46.5  691.8   8.8  13.8  50   2.7   0.0   0.00
oct    3  4  sun  92.6  46.5  691.8   8.8  20.6  24   5.4   0.0   0.00
oct    3  5  wed  91.4  37.9  673.8   5.2  15.9  46   3.6   0.0   0.00
oct    2  5  sun  92.6  46.5  691.8   8.8  15.4  35   0.9   0.0   0.00
oct    8  6  mon  84.9  32.8  664.2   3.0  19.1  32   4.0   0.0   5.44
oct    7  4  mon  91.7  48.5  696.1  11.1  16.8  45   4.5   0.0   6.83
oct    8  6  wed  91.4  37.9  673.8   5.2  20.2  37   2.7   0.0  13.70
oct    4  4  sat  90.6  43.7  686.9   6.7  18.4  25   3.1   0.0  24.23
oct    7  5  mon  91.7  48.5  696.1  11.1  16.1  44   4.0   0.0  49.37
mar    7  5  fri  86.2  26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
mar    8  6  fri  91.7  33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
mar    8  6  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
mar    5  5  sat  91.7  35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
mar    6  4  wed  89.2  27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
mar    4  4  tue  88.1  25.7   67.6   3.8  14.1  43   2.7   0.0   0.00
mar    4  4  mon  87.2  23.9   64.7   4.1  11.8  35   1.8   0.0   0.00
mar    4  4  mon  87.6  52.2  103.8   5.0  11.0  46   5.8   0.0   0.00
mar    2  2  sun  89.3  51.3  102.2   9.6  11.5  39   5.8   0.0   0.00
mar    2  2  sun  89.3  51.3  102.2   9.6   5.5  59   6.3   0.0   0.00
mar    4  5  fri  91.7  33.3   77.5   9.0  17.2  26   4.5   0.0   0.00
mar    4  5  fri  91.2  48.3   97.8  12.5  15.8  27   7.6   0.0   0.00
mar    5  4  fri  91.7  33.3   77.5   9.0  15.6  25   6.3   0.0   0.00
mar    1  3  mon  87.6  52.2  103.8   5.0   8.3  72   3.1   0.0   0.00
mar    6  5  sat  91.7  35.8   80.8   7.8  17.4  25   4.9   0.0   0.00
...   .. ..  ...   ...   ...    ...   ...   ...  ..   ...   ...    ...
mar    3  4  sat  91.7  35.8   80.8   7.8  15.2  27   4.9   0.0   0.00
mar    3  4  mon  90.1  39.7   86.6   6.2  10.6  30   4.0   0.0   0.00
mar    3  5  mon  87.6  52.2  103.8   5.0   9.0  49   2.2   0.0   0.00
mar    4  6  mon  87.2  23.9   64.7   4.1  14.0  39   3.1   0.0   0.00
mar    4  6  sun  89.3  51.3  102.2   9.6  10.6  46   4.9   0.0   0.00
mar    3  5  tue  88.1  25.7   67.6   3.8  14.9  38   2.7   0.0   0.00
mar    5  4  mon  90.1  39.7   86.6   6.2  13.2  40   5.4   0.0   0.95
mar    7  4  mon  90.1  39.7   86.6   6.2  16.1  29   3.1   0.0   1.75
mar    6  3  sat  90.6  50.1  100.4   7.8  15.2  31   8.5   0.0   1.94
mar    6  5  thu  84.9  18.2   55.0   3.0   5.3  70   4.5   0.0   2.14
mar    6  5  fri  91.2  48.3   97.8  12.5  14.6  26   9.4   0.0   2.53
mar    8  6  sun  89.3  51.3  102.2   9.6  11.5  39   5.8   0.0   7.19
mar    6  4  sat  90.8  41.9   89.4   7.9  13.3  42   0.9   0.0   7.40
mar    7  4  sun  90.7  44.0   92.4   5.5  11.5  60   4.0   0.0   8.24
mar    6  5  fri  91.2  48.3   97.8  12.5  11.7  33   4.0   0.0   8.31
mar    6  5  sun  90.1  37.6   83.7   7.2  12.4  54   3.6   0.0  12.10
mar    5  6  sat  90.6  50.1  100.4   7.8  15.1  64   4.0   0.0  13.99
mar    7  3  mon  87.6  52.2  103.8   5.0  11.0  46   5.8   0.0  27.35
mar    4  4  sat  91.7  35.8   80.8   7.8  17.0  27   4.9   0.0  28.66
mar    4  4  sat  91.7  35.8   80.8   7.8  17.0  27   4.9   0.0  28.66
mar    6  5  mon  90.1  39.7   86.6   6.2  15.2  27   3.1   0.0  31.86
mar    4  3  mon  87.6  52.2  103.8   5.0  11.0  46   5.8   0.0  36.85
mar    6  5  thu  90.9  18.9   30.6   8.0   8.7  51   5.8   0.0   0.00
mar    5  5  thu  90.9  18.9   

### 指定行列，选择一个区域

In [105]:
df[["month","day","area"]][:5]

month  day  area
0   mar  fri   0.0
1   oct  tue   0.0
2   oct  sat   0.0
3   mar  fri   0.0
4   mar  sun   0.0

In [106]:
df.loc[0:4,["month","day","area"]]

month  day  area
0   mar  fri   0.0
1   oct  tue   0.0
2   oct  sat   0.0
3   mar  fri   0.0
4   mar  sun   0.0

### 数值型的统计数据

In [8]:
df.describe()

X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000   
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000   

             temp          RH        wind        rain         area  
count  517.000000  517.000000  517.000000  517.000000   517.000000  
mean    18.889168   44.288201    4.017602    0.021663    12.847292  
std      5.806625   16.317469    1.791653    0.295959    63.655818  
min      2.200000   15.000000    0.400000    0.000000     0.000000  
25%     15.500000   33.000000    2.700000    0.000000     0.000000  
50%     19.300000   42.000000    4.000000    0.000000     0.520000  
75%     22.800000   53.000000    4.900000    0.000000     6.570000  
max     33.300000  100.000000    9.400000    6.400000  1090.840000

### 条件选取

创建新的一列，要求满足：
1. 当area >= 6.57 then 'L'
2. 当area < 6.57 并且 >0.52 then "M"
3. else "S"

In [9]:
df.loc[df['area'] >=6.57,"label"] = 'L'
df.loc[(df['area'] < 6.57) & (df['area'] >0.52),"label"] = 'M'
df.loc[df['area'] <= 0.52,'label'] = 'S'

In [10]:
df['label'].value_counts().sum()

517

### iloc只接受索引位选取（行或列皆如此）

In [11]:
df.iloc[:5]

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area label
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0     S
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0     S
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0     S
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0     S
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0     S

In [12]:
df[:5]

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area label
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0     S
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0     S
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0     S
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0     S
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0     S

In [13]:
df.loc[:5]

X  Y month  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain  area label
0  7  5   mar  fri  86.2  26.2   94.3   5.1   8.2  51   6.7   0.0   0.0     S
1  7  4   oct  tue  90.6  35.4  669.1   6.7  18.0  33   0.9   0.0   0.0     S
2  7  4   oct  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.0     S
3  8  6   mar  fri  91.7  33.3   77.5   9.0   8.3  97   4.0   0.2   0.0     S
4  8  6   mar  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.0     S
5  8  6   aug  sun  92.3  85.3  488.0  14.7  22.2  29   5.4   0.0   0.0     S

In [14]:
dfnew.head()

X  Y  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
month                                                               
mar    7  5  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
oct    7  4  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
oct    7  4  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
mar    8  6  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
mar    8  6  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [15]:
dfnew.iloc[:5,['x','y']]          #iloc只能根据索引位来选取的，不可以通过名称来选取的

TypeError: cannot perform reduce with flexible type

修改为如下：

In [18]:
dfnew.iloc[:5,[0,1]]

X  Y
month      
mar    7  5
oct    7  4
oct    7  4
mar    8  6
mar    8  6

### iloc不接受True／False，但loc接受

In [19]:
df.loc[df['area'] >=6.57]

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain    area  \
183  7  4   oct  mon  91.7   48.5  696.1  11.1  16.8  45   4.5   0.0    6.83   
184  8  6   aug  fri  93.9  135.7  586.7  15.1  20.8  34   4.9   0.0    6.96   
185  2  5   sep  tue  91.0  129.5  692.6   7.0  17.6  46   3.1   0.0    7.04   
186  8  6   mar  sun  89.3   51.3  102.2   9.6  11.5  39   5.8   0.0    7.19   
187  1  5   sep  mon  90.9  126.5  686.5   7.0  21.0  42   2.2   0.0    7.30   
188  6  4   mar  sat  90.8   41.9   89.4   7.9  13.3  42   0.9   0.0    7.40   
189  7  4   mar  sun  90.7   44.0   92.4   5.5  11.5  60   4.0   0.0    8.24   
190  6  5   mar  fri  91.2   48.3   97.8  12.5  11.7  33   4.0   0.0    8.31   
191  2  5   aug  thu  95.2  131.7  578.8  10.4  24.2  28   2.7   0.0    8.68   
192  2  2   aug  tue  94.8  108.3  647.1  17.0  24.6  22   4.5   0.0    8.71   
193  4  5   sep  wed  92.9  133.3  699.6   9.2  24.3  25   4.0   0.0    9.41   
194  2  2   aug  tue  94.8  108.3  647.1  17.0  24.6  22   4.5   0.0   10.01   
195  2  5   aug  fri  93.9  135.7  586.7  15.1  23.5  36   5.4   0.0   10.02   
196  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0   10.93   
197  4  5   sep  thu  92.9  137.0  706.4   9.2  21.5  15   0.9   0.0   11.06   
198  3  4   sep  tue  91.0  129.5  692.6   7.0  13.9  59   6.3   0.0   11.24   
199  2  4   sep  mon  63.5   70.8  665.3   0.8  22.6  38   3.6   0.0   11.32   
200  1  5   sep  tue  91.0  129.5  692.6   7.0  21.6  33   2.2   0.0   11.53   
201  6  5   mar  sun  90.1   37.6   83.7   7.2  12.4  54   3.6   0.0   12.10   
202  7  4   feb  sun  83.9    8.7   32.1   2.1   8.8  68   2.2   0.0   13.05   
203  8  6   oct  wed  91.4   37.9  673.8   5.2  20.2  37   2.7   0.0   13.70   
204  5  6   mar  sat  90.6   50.1  100.4   7.8  15.1  64   4.0   0.0   13.99   
205  4  5   sep  thu  92.9  137.0  706.4   9.2  22.1  34   1.8   0.0   14.57   
206  2  2   aug  sat  93.5  139.4  594.2  20.3  22.9  31   7.2   0.0   15.45   
207  7  5   sep  tue  91.0  129.5  692.6   7.0  20.7  37   2.2   0.0   17.20   
208  6  5   sep  fri  92.4  117.9  668.0  12.2  19.6  33   6.3   0.0   19.23   
209  8  3   sep  thu  93.7   80.9  685.2  17.9  23.2  26   4.9   0.0   23.41   
210  4  4   oct  sat  90.6   43.7  686.9   6.7  18.4  25   3.1   0.0   24.23   
211  7  4   aug  sat  93.5  139.4  594.2  20.3   5.1  96   5.8   0.0   26.00   
212  7  4   sep  fri  94.3   85.1  692.3  15.9  20.1  47   4.9   0.0   26.13   
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...     ...   
392  1  3   sep  sun  91.0  276.3  825.1   7.1  21.9  43   4.0   0.0   70.76   
395  4  5   feb  sun  85.0    9.0   56.9   3.5  10.1  62   1.8   0.0   51.78   
400  9  5   jun  wed  93.3   49.5  297.7  14.0  28.0  34   4.5   0.0    8.16   
408  4  3   sep  fri  90.3  290.0  855.3   7.4  19.9  44   3.1   0.0    7.80   
415  8  6   aug  thu  94.8  222.4  698.6  13.9  27.5  27   4.9   0.0  746.28   
416  6  3   jul  tue  92.7  164.1  575.8   8.9  26.3  39   3.1   0.0    7.02   
420  8  8   aug  wed  91.7  191.4  635.9   7.8  26.2  36   4.5   0.0  185.76   
433  2  4   aug  sun  93.6  235.1  723.1  10.1  20.9  66   4.9   0.0   15.34   
444  2  5   sep  fri  90.3  290.0  855.3   7.4  16.2  58   3.6   0.0    9.96   
451  1  4   aug  fri  90.5  196.8  649.9  16.3  11.8  88   4.9   0.0    9.71   
457  1  4   aug  wed  91.7  191.4  635.9   7.8  19.9  50   4.0   0.0   82.75   
465  2  2   feb  sat  79.5    3.6   15.3   1.8   4.6  59   0.9   0.0    6.84   
468  6  5   mar  thu  91.3   20.6   43.5   8.5  13.3  27   3.6   0.0    6.61   
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0   61.13   
471  4  3   may  fri  89.6   25.4   73.7   5.7  18.0  40   4.0   0.0   38.48   
473  9  4   jun  sat  90.5   61.1  252.6   9.4  24.5  50   3.1   0.0   70.32   
474  4  3   jun  thu  93.0  103.8  316.7  10.8  26.4  35   2.7   0.0   10.08   
477  4  3   jul  sun  93.7  101.3  423.4  14.7  26.1  45   4.0   0.0    7.36   
479  

In [20]:
df.iloc[df['area'] >=6.57]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

### ix既可以接受名称，也可以接受位置

In [28]:
dfnew

X  Y  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
month                                                                  
mar    7  5  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
oct    7  4  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
oct    7  4  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
mar    8  6  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
mar    8  6  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
aug    8  6  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
aug    8  6  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
aug    8  6  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
sep    8  6  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
sep    7  5  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
sep    7  5  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
sep    7  5  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
aug    6  5  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
sep    6  5  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
sep    6  5  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
sep    6  5  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
mar    5  5  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
oct    8  5  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
mar    6  4  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
apr    6  4  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
sep    6  4  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
sep    5  4  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
jun    7  4  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
aug    7  4  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
aug    7  4  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
aug    7  4  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
sep    7  4  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
sep    7  4  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
sep    6  3  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
sep    6  3  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
...   .. ..  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
aug    5  4  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
aug    4  4  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
aug    4  4  wed  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
aug    4  4  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
aug    4  4  thu  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
aug    1  3  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
aug    1  3  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
aug    6  6  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
aug    6  6  mon  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
aug    4  5  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
aug    3  4  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
aug    6  5  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
aug    7  5  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
aug    8  6  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
aug    7  5  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
aug    4  4  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
aug    2  4  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
aug    4  3  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
aug    1  2  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
aug    1  2  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
aug    2  4  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
aug    1  2  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
aug    5  4  fri  91.0  166.9  752.6   7.1  21.

In [32]:
dfnew.ix[:5,['day','wind']]

day  wind
month           
mar    fri   6.7
oct    tue   0.9
oct    sat   1.3
mar    fri   4.0
mar    sun   1.8

In [134]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  19   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  18   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  18   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  22   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  22   

  label  
0     S  
1     S  
2     S  
3     S  
4     S

In [26]:
df.ix[0:5,[1,2,4,5]]

Y month  FFMC   DMC
0  5   mar  86.2  26.2
1  4   oct  90.6  35.4
2  4   oct  90.6  43.7
3  6   mar  91.7  33.3
4  6   mar  89.3  51.3
5  6   aug  92.3  85.3

In [131]:
dfnew.loc[:5,['x','y']]

TypeError: cannot do slice indexing on <class 'pandas.indexes.base.Index'> with these indexers [5] of <class 'int'>

In [137]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  19   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  18   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  18   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  22   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  22   

  label  
0     S  
1     S  
2     S  
3     S  
4     S

### query（根据列条件来筛选）

In [34]:
df.query("month == 'mar' & day =='tue' & wind >=7")

X  Y month  day  FFMC   DMC    DC   ISI  temp  RH  wind  rain  area label
114  3  4   mar  tue  88.1  25.7  67.6   3.8  15.8  27   7.6   0.0   0.0     S
393  2  4   mar  tue  93.4  15.0  25.6  11.4  15.2  19   7.6   0.0   0.0     S

## 多重索引

### set_index  &  reset_index

In [43]:
df1 = df.set_index(["month","day"],drop = False)   #drop False原来的索引保留

In [44]:
df1.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  \
month day                                                                  
mar   fri  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   
oct   tue  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   
      sat  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   
mar   fri  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   
      sun  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   

           area label  
month day              
mar   fri   0.0     S  
oct   tue   0.0     S  
      sat   0.0     S  
mar   fri   0.0     S  
      sun   0.0     S

In [39]:
df1 = df.reset_index(["month","day"])

In [40]:
df1.head()

index  X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0      0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1      1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2      2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   
3      3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0   
4      4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0   

  label  
0     S  
1     S  
2     S  
3     S  
4     S

### 条件切片选取先排序

In [47]:
df1.sort_index(inplace=True)

In [50]:
df1.loc['mar','fri']

X  Y month  day  FFMC   DMC    DC   ISI  temp  RH  wind  rain  \
month day                                                                  
mar   fri  7  5   mar  fri  86.2  26.2  94.3   5.1   8.2  51   6.7   0.0   
      fri  8  6   mar  fri  91.7  33.3  77.5   9.0   8.3  97   4.0   0.2   
      fri  4  5   mar  fri  91.7  33.3  77.5   9.0  17.2  26   4.5   0.0   
      fri  4  5   mar  fri  91.2  48.3  97.8  12.5  15.8  27   7.6   0.0   
      fri  5  4   mar  fri  91.7  33.3  77.5   9.0  15.6  25   6.3   0.0   
      fri  8  6   mar  fri  91.7  35.8  80.8   7.8  17.4  24   5.4   0.0   
      fri  4  5   mar  fri  85.9  19.5  57.3   2.8  12.7  52   6.3   0.0   
      fri  4  4   mar  fri  85.9  19.5  57.3   2.8  13.7  43   5.8   0.0   
      fri  3  4   mar  fri  91.7  33.3  77.5   9.0  18.8  18   4.5   0.0   
      fri  6  5   mar  fri  91.2  48.3  97.8  12.5  14.6  26   9.4   0.0   
      fri  6  5   mar  fri  91.2  48.3  97.8  12.5  11.7  33   4.0   0.0   

           area label  
month day              
mar   fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  0.00     S  
      fri  2.53     M  
      fri  8.31     L

In [54]:
df1.loc[('mar','fri'),['X','Y']]     #索引写成元组的形势

X  Y
month day      
mar   fri  7  5
      fri  8  6
      fri  4  5
      fri  4  5
      fri  5  4
      fri  8  6
      fri  4  5
      fri  4  4
      fri  3  4
      fri  6  5
      fri  6  5

In [55]:
df1.loc[('mar',['fri','tue']),['X','Y']]

X  Y
month day      
mar   fri  7  5
      fri  8  6
      fri  4  5
      fri  4  5
      fri  5  4
      fri  8  6
      fri  4  5
      fri  4  4
      fri  3  4
      fri  6  5
      fri  6  5
      tue  4  4
      tue  3  4
      tue  3  5
      tue  3  5
      tue  2  4

In [56]:
df1.loc[(['mar','oct'],['fri','tue']),['X','Y']]

X  Y
month day      
mar   fri  7  5
      fri  8  6
      fri  4  5
      fri  4  5
      fri  5  4
      fri  8  6
      fri  4  5
      fri  4  4
      fri  3  4
      fri  6  5
      fri  6  5
      tue  4  4
      tue  3  4
      tue  3  5
      tue  3  5
      tue  2  4
oct   fri  7  4
      tue  7  4
      tue  6  3

### slice

In [57]:
df1.loc[(slice('apr','sep'),['fri','tue']),]  # , 用于区分行和列的

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  \
month day                                                                    
apr   fri  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0   
aug   fri  6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   
      fri  1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0   
      fri  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0   
      fri  8  6   aug  fri  93.9  135.7  586.7  15.1  20.8  34   4.9   0.0   
      fri  2  5   aug  fri  93.9  135.7  586.7  15.1  23.5  36   5.4   0.0   
      fri  3  4   aug  fri  91.6  112.4  573.0   8.9  11.2  84   7.6   0.0   
      fri  2  4   aug  fri  91.6  112.4  573.0   8.9  21.4  42   3.1   0.0   
      fri  6  3   aug  fri  91.1  141.1  629.1   7.1  19.3  39   3.6   0.0   
      fri  4  4   aug  fri  94.3  167.6  684.4  13.0  21.8  53   3.1   0.0   
      fri  6  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1   0.0   
      fri  7  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1   0.0   
      fri  9  9   aug  fri  94.8  227.0  706.7  12.0  25.0  36   4.0   0.0   
      fri  1  4   aug  fri  90.6  269.8  811.2   5.5  22.2  45   3.6   0.0   
      fri  1  4   aug  fri  90.5  196.8  649.9  16.3  11.8  88   4.9   0.0   
      fri  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   
      fri  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0   
      fri  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   
      fri  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   
      fri  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   
      fri  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   
      fri  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   
      tue  4  4   aug  tue  94.8  108.3  647.1  17.0  16.6  54   5.4   0.0   
      tue  5  4   aug  tue  88.8  147.3  614.5   9.0  17.3  43   4.5   0.0   
      tue  1  2   aug  tue  91.0  121.2  561.6   7.0  21.6  19   6.7   0.0   
      tue  1  2   aug  tue  94.8  108.3  647.1  17.0  18.6  51   4.5   0.0   
      tue  3  4   aug  tue  88.8  147.3  614.5   9.0  14.4  66   5.4   0.0   
      tue  2  4   aug  tue  94.8  108.3  647.1  17.0  20.1  40   4.0   0.0   
      tue  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0   
      tue  8  6   aug  tue  88.8  147.3  614.5   9.0  14.4  66   5.4   0.0   
...       .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...   
sep   fri  6  3   sep  fri  92.5  122.0  789.7  10.2  19.7  39   2.7   0.0   
      fri  1  4   sep  fri  92.5  122.0  789.7  10.2  21.1  39   2.2   0.0   
      fri  6  5   sep  fri  92.5  122.0  789.7  10.2  18.4  42   2.2   0.0   
      fri  4  3   sep  fri  92.5  122.0  789.7  10.2  17.3  45   4.0   0.0   
      fri  7  4   sep  fri  88.2   55.2  732.3  11.6  15.2  64   3.1   0.0   
      fri  6  5   sep  fri  90.3  290.0  855.3   7.4  10.3  78   4.0   0.0   
      fri  8  6   sep  fri  91.1   91.3  738.1   7.2  20.7  46   2.7   0.0   
      fri  4  3   sep  fri  90.3  290.0  855.3   7.4  19.9  44   3.1   0.0   
      fri  1  3   sep  fri  91.1   91.3  738.1   7.2  19.1  46   2.2   0.0   
      fri  5  4   sep  fri  90.3  290.0  855.3   7.4  16.2  58   3.6   0.0   
      fri  2  5   sep  fri  90.3  290.0  855.3   7.4  16.2  58   3.6   0.0   
      tue  8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   
      tue  6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   
      tue  6  3   sep  tue  90.3   80.7  730.2   6.3  18.2  62   4.5   0.0   
      tue  4  3   sep  tue  90.3   80.7  730.2   6.3  17.8  63   4.9   0.0   
      tue  3  4   sep  tue  84.4   73.4  671.9   3.2  17.9  45   3.1   0.0   
      tue  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0   
      tue  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0   
      tue  2  5   sep  tue  91.0 

In [46]:
df1.loc[(slice(None),['fri','tue']),]      #表示month索引没有筛选，全部都要，day索引选择fri和tue的

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  \
month day                                                                    
apr   fri  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0   
aug   fri  6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   
      fri  1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0   
      fri  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0   
      fri  8  6   aug  fri  93.9  135.7  586.7  15.1  20.8  34   4.9   0.0   
      fri  2  5   aug  fri  93.9  135.7  586.7  15.1  23.5  36   5.4   0.0   
      fri  3  4   aug  fri  91.6  112.4  573.0   8.9  11.2  84   7.6   0.0   
      fri  2  4   aug  fri  91.6  112.4  573.0   8.9  21.4  42   3.1   0.0   
      fri  6  3   aug  fri  91.1  141.1  629.1   7.1  19.3  39   3.6   0.0   
      fri  4  4   aug  fri  94.3  167.6  684.4  13.0  21.8  53   3.1   0.0   
      fri  6  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1   0.0   
      fri  7  4   aug  fri  94.8  227.0  706.7  12.0  23.3  34   3.1   0.0   
      fri  9  9   aug  fri  94.8  227.0  706.7  12.0  25.0  36   4.0   0.0   
      fri  1  4   aug  fri  90.6  269.8  811.2   5.5  22.2  45   3.6   0.0   
      fri  1  4   aug  fri  90.5  196.8  649.9  16.3  11.8  88   4.9   0.0   
      fri  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   
      fri  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0   
      fri  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   
      fri  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   
      fri  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   
      fri  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   
      fri  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   
      tue  4  4   aug  tue  94.8  108.3  647.1  17.0  16.6  54   5.4   0.0   
      tue  5  4   aug  tue  88.8  147.3  614.5   9.0  17.3  43   4.5   0.0   
      tue  1  2   aug  tue  91.0  121.2  561.6   7.0  21.6  19   6.7   0.0   
      tue  1  2   aug  tue  94.8  108.3  647.1  17.0  18.6  51   4.5   0.0   
      tue  3  4   aug  tue  88.8  147.3  614.5   9.0  14.4  66   5.4   0.0   
      tue  2  4   aug  tue  94.8  108.3  647.1  17.0  20.1  40   4.0   0.0   
      tue  2  2   aug  tue  94.8  108.3  647.1  17.0  17.4  43   6.7   0.0   
      tue  8  6   aug  tue  88.8  147.3  614.5   9.0  14.4  66   5.4   0.0   
...       .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...   
sep   fri  6  3   sep  fri  92.5  122.0  789.7  10.2  19.7  39   2.7   0.0   
      fri  1  4   sep  fri  92.5  122.0  789.7  10.2  21.1  39   2.2   0.0   
      fri  6  5   sep  fri  92.5  122.0  789.7  10.2  18.4  42   2.2   0.0   
      fri  4  3   sep  fri  92.5  122.0  789.7  10.2  17.3  45   4.0   0.0   
      fri  7  4   sep  fri  88.2   55.2  732.3  11.6  15.2  64   3.1   0.0   
      fri  6  5   sep  fri  90.3  290.0  855.3   7.4  10.3  78   4.0   0.0   
      fri  8  6   sep  fri  91.1   91.3  738.1   7.2  20.7  46   2.7   0.0   
      fri  4  3   sep  fri  90.3  290.0  855.3   7.4  19.9  44   3.1   0.0   
      fri  1  3   sep  fri  91.1   91.3  738.1   7.2  19.1  46   2.2   0.0   
      fri  5  4   sep  fri  90.3  290.0  855.3   7.4  16.2  58   3.6   0.0   
      fri  2  5   sep  fri  90.3  290.0  855.3   7.4  16.2  58   3.6   0.0   
      tue  8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   
      tue  6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   
      tue  6  3   sep  tue  90.3   80.7  730.2   6.3  18.2  62   4.5   0.0   
      tue  4  3   sep  tue  90.3   80.7  730.2   6.3  17.8  63   4.9   0.0   
      tue  3  4   sep  tue  84.4   73.4  671.9   3.2  17.9  45   3.1   0.0   
      tue  1  4   sep  tue  91.0  129.5  692.6   7.0  21.7  38   2.2   0.0   
      tue  8  3   sep  tue  84.4   73.4  671.9   3.2  24.2  28   3.6   0.0   
      tue  2  5   sep  tue  91.0 

In [193]:
df.index

RangeIndex(start=0, stop=517, step=1)

In [194]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  19   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  18   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  18   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  22   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  22   

  label  
0     S  
1     S  
2     S  
3     S  
4     S

In [195]:
grouped = df.groupby(['month','day'])

In [199]:
len(grouped)

64

In [197]:
grouped.head()

x  y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain    area  \
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0    0.00   
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0    0.00   
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0    0.00   
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2    0.00   
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0    0.00   
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0    0.00   
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0    0.00   
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0    0.00   
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0    0.00   
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0    0.00   
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0    0.00   
11   7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0    0.00   
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0    0.00   
13   6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0    0.00   
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0    0.00   
15   6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0    0.00   
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0    0.00   
17   8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0    0.00   
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0    0.00   
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0    0.00   
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0    0.00   
21   5  4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0    0.00   
22   7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0    0.00   
23   7  4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0    0.00   
24   7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0    0.00   
25   7  4   aug  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0    0.00   
26   7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0    0.00   
27   7  4   sep  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0    0.00   
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0    0.00   
29   6  3   sep  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0    0.00   
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...     ...   
407  4  5   feb  sat  84.7    8.2   55.0   2.9  14.2  46   4.0   0.0    0.00   
409  1  4   jul  tue  92.3   96.2  450.2  12.1  23.4  31   5.4   0.0    0.00   
410  6  3   feb  fri  84.1    7.3   52.8   2.7  14.7  42   2.7   0.0    0.00   
411  7  4   feb  fri  84.6    3.2   43.6   3.3   8.2  53   9.4   0.0    4.62   
412  9  4   jul  mon  92.3   92.1  442.1   9.8  22.8  27   4.5   0.0    1.63   
417  6  5   mar  wed  93.4   17.3   28.3   9.9  13.8  24   5.8   0.0    0.00   
422  8  6   jul  sun  88.9  263.1  795.9   5.2  29.3  27   3.6   0.0    6.30   
442  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1   0.0    3.35   
443  1  2   jul  fri  90.7   80.9  368.3  16.8  14.8  78   8.0   0.0    0.00   
447  3  4   mar  wed  93.4   17.3   28.3   9.9   8.9  35   8.0   0.0    0.00   
455  3  4   jul  mon  94.6  160.0  567.2  16.7  17.9  48   2.7   0.0    0.00   
463  6  5   feb  tue  75.1    4.4   16.2   1.9   4.6  82   6.3   0.0    5.39   
464  6  4   feb  tue  75.1    4.4   16.2   1.9   5.1  77   5.4   0.0    2.14   
465  2  2   feb  sat  79.5    3.6   15.3   1.8   4.6  59   0.9   0.0    6.84   
467  3  4   mar  wed  90.2   18.5   41.1   7.3  11.2  41   5.4   0.0    5.55   
468  6  5   mar  thu  91.3   20.6   43.5   8.5  13.3  27   3.6   0.0    6.61   
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0   61.13   
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8   0.0    0.00   
471  

# 分组计算

In [58]:
import numpy as np 

In [65]:
grouped = df.groupby(['month','day'])

In [66]:
len(grouped)

64

In [64]:
grouped.size()

month  day
apr    fri     1
       mon     1
       sat     1
       sun     3
       thu     2
       wed     1
aug    fri    21
       mon    15
       sat    29
       sun    40
       thu    26
       tue    28
       wed    25
dec    fri     1
       mon     4
       sun     1
       thu     1
       tue     1
       wed     1
feb    fri     5
       mon     3
       sat     4
       sun     4
       thu     1
       tue     2
       wed     1
jan    sat     1
       sun     1
jul    fri     3
       mon     4
              ..
       wed     3
jun    fri     3
       mon     3
       sat     2
       sun     4
       thu     2
       wed     3
mar    fri    11
       mon    12
       sat    10
       sun     7
       thu     5
       tue     5
       wed     4
may    fri     1
       sat     1
nov    tue     1
oct    fri     1
       mon     4
       sat     3
       sun     3
       tue     2
       wed     2
sep    fri    38
       mon    28
       sat    25
       sun    27
   

In [67]:
grouped.sum()

X    Y    FFMC     DMC       DC    ISI   temp    RH   wind  rain  \
month day                                                                       
apr   fri    4    4    83.0    23.3     85.3    2.3   16.7    20    3.1   0.0   
      mon    6    5    87.9    24.9     41.6    3.7   10.9    64    3.1   0.0   
      sat    6    4    86.3    27.4     97.1    5.1    9.3    44    4.5   0.0   
      sun   18   12   263.9    32.2     59.1   28.1   44.7   135   17.0   0.0   
      thu   12   10   163.0    18.2    110.4    5.4   11.6   108   11.6   0.0   
      wed    6    3    88.0    17.2     43.5    3.8   15.2    51    2.7   0.0   
aug   fri   81   87  1912.4  3389.8  13969.2  209.8  446.0  1058  100.1   1.4   
      mon   79   73  1389.9  2382.1   9480.7  161.8  340.4   627   43.1   0.0   
      sat  145  129  2686.1  4933.9  18909.8  323.4  594.6  1392  125.0   0.0   
      sun  180  175  3639.5  5490.3  24643.3  380.2  850.3  1919  176.7   1.0   
      thu  120  109  2407.7  4445.8  17135.5  225.4  556.6  1106   91.1   0.0   
      tue  112  107  2623.3  4085.0  17919.8  407.5  611.6  1295  127.9   8.4   
      wed  108  108  2331.1  3559.9  15900.0  329.2  580.7   973   88.0   0.0   
dec   fri    4    6    84.7    26.7    352.6    4.1    2.2    59    4.9   0.0   
      mon   15   16   341.6   101.6   1398.8   10.4   18.4    84   34.0   0.0   
      sun    4    6    84.4    27.2    353.5    6.8    4.8    57    8.5   0.0   
      thu    4    6    84.6    26.4    352.0    2.0    5.1    61    4.9   0.0   
      tue    6    5    85.4    25.4    349.7    2.6    5.1    24    8.5   0.0   
      wed    8    6    84.0    27.8    354.6    5.3    5.1    61    8.0   0.0   
feb   fri   29   22   427.1    41.8    198.2   22.9   58.4   235   24.1   0.0   
      mon   15   11   252.8    23.4    139.0    8.4   26.7   179   13.5   0.0   
      sat   13   17   316.3    41.3    187.7    8.1   46.9   193    9.4   0.0   
      sun   22   16   340.6    60.8    490.8   12.9   35.5   234   10.2   0.0   
      thu    9    9    84.2     6.8     26.6    7.7    6.7    79    3.1   0.0   
      tue   12    9   150.2     8.8     32.4    3.8    9.7   159   11.7   0.0   
      wed    3    4    86.9     6.6     18.7    3.2    8.8    35    3.1   0.0   
jan   sat    2    4    82.1     3.7      9.3    2.9    5.3    78    3.1   0.0   
      sun    4    5    18.7     1.1    171.4    0.0    5.2   100    0.9   0.0   
jul   fri    7    9   270.6   331.4   1144.5   29.9   51.1   197   12.9   0.0   
      mon   25   18   370.3   418.3   1883.8   43.9   86.3   168   15.2   0.0   
...        ...  ...     ...     ...      ...    ...    ...   ...    ...   ...   
      wed   15   14   276.8   418.0   1417.0   32.4   46.1   187   18.8   0.2   
jun   fri   12   17   274.7   244.6    897.5   21.3   61.6   115   14.4   0.0   
      mon   20   13   269.0   282.8    825.2   19.7   54.1   143   14.3   0.0   
      sat   15    9   143.9   132.1    486.4    9.8   35.1   140    5.8   0.0   
      sun   28   19   368.2   455.7   1212.4   79.9   72.9   183    9.8   0.0   
      thu    6    8   186.7   225.5    666.9   28.8   49.1    75   12.1   0.0   
      wed   26   16   277.8   246.8    972.6   40.7   75.6   111   13.9   0.0   
mar   fri   59   54   990.1   379.1    893.1   92.0  154.0   422   64.5   0.2   
      mon   54   50  1060.0   482.7   1031.7   65.1  141.4   504   49.0   0.0   
      sat   45   43   891.2   359.3    790.5   71.0  154.3   324   50.1   0.0   
      sun   37   31   627.3   338.1    687.1   60.7   74.4   396   32.2   0.0   
      thu   27   25   449.4   107.3    234.0   35.0   57.1   225   22.4   0.0   
      tue   15   22   445.8   117.8    296.0   26.6   75.5   154   26.9   0.0   
      wed   18   17   366.2    81.0    168.5   33.4   49.8   135   23.2   0.0   
may   fri    4    3    89.6    25.4     73.7    5.7   18.0    40    4.0   0.0   
      sat    6    5    85.1    28.0    113.8    3.5   11.3    94    4.9   0.0   
nov   tue    6    3    79.5     3.0    106.7

In [69]:
grouped.mean()

X         Y       FFMC         DMC          DC        ISI  \
month day                                                                     
apr   fri  4.000000  4.000000  83.000000   23.300000   85.300000   2.300000   
      mon  6.000000  5.000000  87.900000   24.900000   41.600000   3.700000   
      sat  6.000000  4.000000  86.300000   27.400000   97.100000   5.100000   
      sun  6.000000  4.000000  87.966667   10.733333   19.700000   9.366667   
      thu  6.000000  5.000000  81.500000    9.100000   55.200000   2.700000   
      wed  6.000000  3.000000  88.000000   17.200000   43.500000   3.800000   
aug   fri  3.857143  4.142857  91.066667  161.419048  665.200000   9.990476   
      mon  5.266667  4.866667  92.660000  158.806667  632.046667  10.786667   
      sat  5.000000  4.448276  92.624138  170.134483  652.062069  11.151724   
      sun  4.500000  4.375000  90.987500  137.257500  616.082500   9.505000   
      thu  4.615385  4.192308  92.603846  170.992308  659.057692   8.669231   
      tue  4.000000  3.821429  93.689286  145.892857  639.992857  14.553571   
      wed  4.320000  4.320000  93.244000  142.396000  636.000000  13.168000   
dec   fri  4.000000  6.000000  84.700000   26.700000  352.600000   4.100000   
      mon  3.750000  4.000000  85.400000   25.400000  349.700000   2.600000   
      sun  4.000000  6.000000  84.400000   27.200000  353.500000   6.800000   
      thu  4.000000  6.000000  84.600000   26.400000  352.000000   2.000000   
      tue  6.000000  5.000000  85.400000   25.400000  349.700000   2.600000   
      wed  8.000000  6.000000  84.000000   27.800000  354.600000   5.300000   
feb   fri  5.800000  4.400000  85.420000    8.360000   39.640000   4.580000   
      mon  5.000000  3.666667  84.266667    7.800000   46.333333   2.800000   
      sat  3.250000  4.250000  79.075000   10.325000   46.925000   2.025000   
      sun  5.500000  4.000000  85.150000   15.200000  122.700000   3.225000   
      thu  9.000000  9.000000  84.200000    6.800000   26.600000   7.700000   
      tue  6.000000  4.500000  75.100000    4.400000   16.200000   1.900000   
      wed  3.000000  4.000000  86.900000    6.600000   18.700000   3.200000   
jan   sat  2.000000  4.000000  82.100000    3.700000    9.300000   2.900000   
      sun  4.000000  5.000000  18.700000    1.100000  171.400000   0.000000   
jul   fri  2.333333  3.000000  90.200000  110.466667  381.500000   9.966667   
      mon  6.250000  4.500000  92.575000  104.575000  470.950000  10.975000   
...             ...       ...        ...         ...         ...        ...   
      wed  5.000000  4.666667  92.266667  139.333333  472.333333  10.800000   
jun   fri  4.000000  5.666667  91.566667   81.533333  299.166667   7.100000   
      mon  6.666667  4.333333  89.666667   94.266667  275.066667   6.566667   
      sat  7.500000  4.500000  71.950000   66.050000  243.200000   4.900000   
      sun  7.000000  4.750000  92.050000  113.925000  303.100000  19.975000   
      thu  3.000000  4.000000  93.350000  112.750000  333.450000  14.400000   
      wed  8.666667  5.333333  92.600000   82.266667  324.200000  13.566667   
mar   fri  5.363636  4.909091  90.009091   34.463636   81.190909   8.363636   
      mon  4.500000  4.166667  88.333333   40.225000   85.975000   5.425000   
      sat  4.500000  4.300000  89.120000   35.930000   79.050000   7.100000   
      sun  5.285714  4.428571  89.614286   48.300000   98.157143   8.671429   
      thu  5.400000  5.000000  89.880000   21.460000   46.800000   7.000000   
      tue  3.000000  4.400000  89.160000   23.560000   59.200000   5.320000   
      wed  4.500000  4.250000  91.550000   20.250000   42.125000   8.350000   
may   fri  4.000000  3.000000  89.600000   25.400000   73.700000   5.700000   
      sat  6.000000  5.000000  85.100000   28.000000  113.800000   3.500000   
nov   tue  6.000000  3.000000  79.500000    3.000000  106.700000   1.100000   
oct   fri  7.000000  4.000000  90.000000   41.500000  682.600000   8

In [71]:
grouped['X','Y'].median()

X    Y
month day          
apr   fri  4.0  4.0
      mon  6.0  5.0
      sat  6.0  4.0
      sun  6.0  4.0
      thu  6.0  5.0
      wed  6.0  3.0
aug   fri  3.0  4.0
      mon  6.0  5.0
      sat  6.0  4.0
      sun  4.0  4.0
      thu  4.0  4.0
      tue  4.0  4.0
      wed  4.0  4.0
dec   fri  4.0  6.0
      mon  4.0  4.0
      sun  4.0  6.0
      thu  4.0  6.0
      tue  6.0  5.0
      wed  8.0  6.0
feb   fri  6.0  4.0
      mon  6.0  4.0
      sat  3.5  4.5
      sun  5.5  4.0
      thu  9.0  9.0
      tue  6.0  4.5
      wed  3.0  4.0
jan   sat  2.0  4.0
      sun  4.0  5.0
jul   fri  2.0  2.0
      mon  6.5  4.0
...        ...  ...
      wed  5.0  4.0
jun   fri  3.0  6.0
      mon  6.0  5.0
      sat  7.5  4.5
      sun  7.0  4.5
      thu  3.0  4.0
      wed  9.0  5.0
mar   fri  5.0  5.0
      mon  4.0  4.0
      sat  4.5  4.0
      sun  6.0  5.0
      thu  6.0  5.0
      tue  3.0  4.0
      wed  4.5  4.0
may   fri  4.0  3.0
      sat  6.0  5.0
nov   tue  6.0  3.0
oct   fri  7.0  4.0
      mon  7.5  5.0
      sat  7.0  4.0
      sun  3.0  4.0
      tue  6.5  3.5
      wed  5.5  5.5
sep   fri  5.0  4.0
      mon  4.0  4.0
      sat  5.0  5.0
      sun  3.0  4.0
      thu  4.0  4.0
      tue  4.0  4.0
      wed  4.0  4.0

[64 rows x 2 columns]

### aggregate

In [72]:
grouped['X','Y'].aggregate([np.sum,np.median,np.mean])

X                     Y                 
           sum median      mean  sum median      mean
month day                                            
apr   fri    4    4.0  4.000000    4    4.0  4.000000
      mon    6    6.0  6.000000    5    5.0  5.000000
      sat    6    6.0  6.000000    4    4.0  4.000000
      sun   18    6.0  6.000000   12    4.0  4.000000
      thu   12    6.0  6.000000   10    5.0  5.000000
      wed    6    6.0  6.000000    3    3.0  3.000000
aug   fri   81    3.0  3.857143   87    4.0  4.142857
      mon   79    6.0  5.266667   73    5.0  4.866667
      sat  145    6.0  5.000000  129    4.0  4.448276
      sun  180    4.0  4.500000  175    4.0  4.375000
      thu  120    4.0  4.615385  109    4.0  4.192308
      tue  112    4.0  4.000000  107    4.0  3.821429
      wed  108    4.0  4.320000  108    4.0  4.320000
dec   fri    4    4.0  4.000000    6    6.0  6.000000
      mon   15    4.0  3.750000   16    4.0  4.000000
      sun    4    4.0  4.000000    6    6.0  6.000000
      thu    4    4.0  4.000000    6    6.0  6.000000
      tue    6    6.0  6.000000    5    5.0  5.000000
      wed    8    8.0  8.000000    6    6.0  6.000000
feb   fri   29    6.0  5.800000   22    4.0  4.400000
      mon   15    6.0  5.000000   11    4.0  3.666667
      sat   13    3.5  3.250000   17    4.5  4.250000
      sun   22    5.5  5.500000   16    4.0  4.000000
      thu    9    9.0  9.000000    9    9.0  9.000000
      tue   12    6.0  6.000000    9    4.5  4.500000
      wed    3    3.0  3.000000    4    4.0  4.000000
jan   sat    2    2.0  2.000000    4    4.0  4.000000
      sun    4    4.0  4.000000    5    5.0  5.000000
jul   fri    7    2.0  2.333333    9    2.0  3.000000
      mon   25    6.5  6.250000   18    4.0  4.500000
...        ...    ...       ...  ...    ...       ...
      wed   15    5.0  5.000000   14    4.0  4.666667
jun   fri   12    3.0  4.000000   17    6.0  5.666667
      mon   20    6.0  6.666667   13    5.0  4.333333
      sat   15    7.5  7.500000    9    4.5  4.500000
      sun   28    7.0  7.000000   19    4.5  4.750000
      thu    6    3.0  3.000000    8    4.0  4.000000
      wed   26    9.0  8.666667   16    5.0  5.333333
mar   fri   59    5.0  5.363636   54    5.0  4.909091
      mon   54    4.0  4.500000   50    4.0  4.166667
      sat   45    4.5  4.500000   43    4.0  4.300000
      sun   37    6.0  5.285714   31    5.0  4.428571
      thu   27    6.0  5.400000   25    5.0  5.000000
      tue   15    3.0  3.000000   22    4.0  4.400000
      wed   18    4.5  4.500000   17    4.0  4.250000
may   fri    4    4.0  4.000000    3    3.0  3.000000
      sat    6    6.0  6.000000    5    5.0  5.000000
nov   tue    6    6.0  6.000000    3    3.0  3.000000
oct   fri    7    7.0  7.000000    4    4.0  4.000000
      mon   30    7.5  7.500000   20    5.0  5.000000
      sat   18    7.0  6.000000   11    4.0  3.666667
      sun    9    3.0  3.000000   12    4.0  4.000000
      tue   13    6.5  6.500000    7    3.5  3.500000
      wed   11    5.5  5.500000   11    5.5  5.500000
sep   fri  181    5.0  4.763158  148    4.0  3.894737
      mon  118    4.0  4.214286  117    4.0  4.178571
      sat  115    5.0  4.600000  108    5.0  4.320000
      sun   98    3.0  3.629630  107    4.0  3.962963
      thu   90    4.0  4.285714   86    4.0  4.095238
      tue   89    4.0  4.684211   79    4.0  4.157895
      wed   63    4.0  4.500000   63    4.0  4.500000

[64 rows x 6 columns]

In [216]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  19   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  18   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  18   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  22   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  22   

  label  
0     S  
1     S  
2     S  
3     S  
4     S

In [217]:
grouped.agg({"DMC":np.sum,"DC":np.mean,"ISI":np.median})

DMC          DC    ISI
month day                           
apr   fri    23.3   85.300000   2.30
      mon    24.9   41.600000   3.70
      sat    27.4   97.100000   5.10
      sun    32.2   19.700000  12.30
      thu    18.2   55.200000   2.70
      wed    17.2   43.500000   3.80
aug   fri  3389.8  665.200000  11.30
      mon  2382.1  632.046667   8.50
      sat  4933.9  652.062069   8.90
      sun  5490.3  616.082500  10.35
      thu  4445.8  659.057692   7.25
      tue  4085.0  639.992857  14.30
      wed  3559.9  636.000000  13.50
dec   fri    26.7  352.600000   4.10
      mon   101.6  349.700000   2.60
      sun    27.2  353.500000   6.80
      thu    26.4  352.000000   2.00
      tue    25.4  349.700000   2.60
      wed    27.8  354.600000   5.30
feb   fri    41.8   39.640000   5.30
      mon    23.4   46.333333   2.20
      sat    41.3   46.925000   2.20
      sun    60.8  122.700000   3.45
      thu     6.8   26.600000   7.70
      tue     8.8   16.200000   1.90
      wed     6.6   18.700000   3.20
jan   sat     3.7    9.300000   2.90
      sun     1.1  171.400000   0.00
jul   fri   331.4  381.500000   6.80
      mon   418.3  470.950000  10.40
...           ...         ...    ...
      wed   418.0  472.333333  11.90
jun   fri   244.6  299.166667   7.10
      mon   282.8  275.066667   7.50
      sat   132.1  243.200000   4.90
      sun   455.7  303.100000   8.70
      thu   225.5  333.450000  14.40
      wed   246.8  324.200000  14.00
mar   fri   379.1   81.190909   9.00
      mon   482.7   85.975000   5.00
      sat   359.3   79.050000   7.80
      sun   338.1   98.157143   9.60
      thu   107.3   46.800000   8.00
      tue   117.8   59.200000   3.80
      wed    81.0   42.125000   8.60
may   fri    25.4   73.700000   5.70
      sat    28.0  113.800000   3.50
nov   tue     3.0  106.700000   1.10
oct   fri    41.5  682.600000   8.70
      mon   162.6  680.150000   7.05
      sat   131.1  686.900000   6.70
      sun   139.5  691.800000   8.80
      tue    70.8  669.100000   6.70
      wed    75.8  673.800000   5.20
sep   fri  4773.3  738.889474  10.20
      mon  3075.9  737.439286   7.00
      sat  2903.7  729.480000   8.40
      sun  3608.8  736.318519   8.10
      thu  2554.7  739.400000   8.60
      tue  2146.8  718.136842   7.00
      wed  1735.5  738.442857   9.00

[64 rows x 3 columns]

In [75]:
for name,group in grouped:
    print (name)
    print (group.head())

('apr', 'fri')
     X  Y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area label
241  4  4   apr  fri  83.0  23.3  85.3  2.3  16.7  20   3.1   0.0   0.0     S
('apr', 'mon')
     X  Y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area label
442  6  5   apr  mon  87.9  24.9  41.6  3.7  10.9  64   3.1   0.0  3.35     M
('apr', 'sat')
    X  Y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area label
19  6  4   apr  sat  86.3  27.4  97.1  5.1   9.3  44   4.5   0.0   0.0     S
('apr', 'sun')
     X  Y month  day  FFMC   DMC    DC   ISI  temp  RH  wind  rain   area  \
239  7  5   apr  sun  81.9   3.0   7.9   3.5  13.4  75   1.8   0.0   0.00   
469  6  3   apr  sun  91.0  14.6  25.6  12.3  13.7  33   9.4   0.0  61.13   
470  5  4   apr  sun  91.0  14.6  25.6  12.3  17.6  27   5.8   0.0   0.00   

    label  
239     S  
469     L  
470     S  
('apr', 'thu')
     X  Y month  day  FFMC  DMC    DC  ISI  temp  RH  wind  rain   area label
176  6  5   apr  thu  81

In [223]:
df1.drop(['month','day'],axis = 1,inplace = True)

In [224]:
df1.head()

x  y  FFMC   DMC    DC   ISI  temp  RH  wind  rain   area  xx label
month day                                                                     
apr   fri  4  4  83.0  23.3  85.3   2.3  16.7  20   3.1   0.0   0.00  12     S
      mon  6  5  87.9  24.9  41.6   3.7  10.9  64   3.1   0.0   3.35  17     M
      sat  6  4  86.3  27.4  97.1   5.1   9.3  44   4.5   0.0   0.00  16     S
      sun  7  5  81.9   3.0   7.9   3.5  13.4  75   1.8   0.0   0.00  19     S
      sun  6  3  91.0  14.6  25.6  12.3  13.7  33   9.4   0.0  61.13  15     L

# 多表操作

In [3]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                'B': ['B0', 'B1', 'B2', 'B3'],
                 'C': ['C0', 'C1', 'C2', 'C3'],
                'D': ['D0', 'D1', 'D2', 'D3']},
                 index=[0, 1, 2, 3])   

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                  'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                  'D': ['D4', 'D5', 'D6', 'D7']},
                     index=[4, 5, 6, 7])


df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                   'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                   'D': ['D8', 'D9', 'D10', 'D11']},
                  index=[8, 9, 10, 11])

df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
              'D': ['D2', 'D3', 'D6', 'D7'],
             'F': ['F2', 'F3', 'F6', 'F7']},
             index=[2, 3, 6, 7])


In [4]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [269]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [270]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

## concat

In [5]:
pd.concat([df1,df2,df3],axis = 0)  #默认是0，在行上面

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [6]:
pd.concat([df1,df2,df3],axis = 1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

## merge

In [7]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})
 

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                       'key2': ['K0', 'K0', 'K0', 'K0'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})


In [277]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [278]:
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [8]:
pd.merge(left,right,how = "inner",on = ['key1','key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [9]:
right1 = right.rename(columns = {"key1":"key1_right"})

In [10]:
right1

C   D key1_right key2
0  C0  D0         K0   K0
1  C1  D1         K1   K0
2  C2  D2         K1   K0
3  C3  D3         K2   K0

In [11]:
pd.merge(left,right1,how = "inner",left_on = ['key1','key2'],right_on = ['key1_right','key2'])

A   B key1 key2   C   D key1_right
0  A0  B0   K0   K0  C0  D0         K0
1  A2  B2   K1   K0  C1  D1         K1
2  A2  B2   K1   K0  C2  D2         K1

## right_index

In [285]:
right2 = right.set_index(['key1','key2'])

In [286]:
right2

C   D
key1 key2        
K0   K0    C0  D0
K1   K0    C1  D1
     K0    C2  D2
K2   K0    C3  D3

In [287]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [290]:
pd.merge(left,right2,how = "inner",left_on = ['key1','key2'],right_index =True)

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
2  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

# 内置函数(enumerate,zip)

In [12]:
alist = ['a','b','c']

## enumerate

In [13]:
list(enumerate(alist))

[(0, 'a'), (1, 'b'), (2, 'c')]

In [16]:
df.iloc[:5,:9]

X  Y month  day  FFMC   DMC     DC  ISI  temp
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4

In [17]:
list(enumerate(df.columns))

[(0, 'X'),
 (1, 'Y'),
 (2, 'month'),
 (3, 'day'),
 (4, 'FFMC'),
 (5, 'DMC'),
 (6, 'DC'),
 (7, 'ISI'),
 (8, 'temp'),
 (9, 'RH'),
 (10, 'wind'),
 (11, 'rain'),
 (12, 'area')]

bdir = {}
for i in enumerate(df.columns):
    bdir[i[]]

In [18]:
bdir = {}
for i in enumerate(df.columns):
    bdir[i[1]] = i[0]

In [21]:
bdir

{'DC': 6,
 'DMC': 5,
 'FFMC': 4,
 'ISI': 7,
 'RH': 9,
 'X': 0,
 'Y': 1,
 'area': 12,
 'day': 3,
 'month': 2,
 'rain': 11,
 'temp': 8,
 'wind': 10}

In [23]:
bdir['temp']

8

In [308]:
df.iloc[:5,14]

0    S
1    S
2    S
3    S
4    S
Name: label, dtype: object

## zip

In [24]:
a = [1,2,3,4]
b = ['a','b','c']

In [25]:
list(zip(a,b))

[(1, 'a'), (2, 'b'), (3, 'c')]

# 数据透视表

## pivot_table

In [316]:
pd.pivot_table(df,index='y',columns='x',values=['FFMC','DMC'],aggfunc=np.mean)

FFMC                                                         \
x          1          2          3          4          5          6   
y                                                                     
2  91.968421  91.132000        NaN        NaN        NaN        NaN   
3  92.060000  91.600000  92.200000  91.445455        NaN  90.444000   
4  91.506667  89.188889  90.611628  90.866667  91.852174  89.311111   
5  92.200000  92.240000  90.414286  88.332000  92.200000  89.012245   
6        NaN        NaN  91.375000  85.700000  91.850000  95.466667   
8        NaN        NaN        NaN        NaN        NaN        NaN   
9        NaN        NaN        NaN        NaN        NaN        NaN   

                                           DMC                          \
x          7          8          9           1           2           3   
y                                                                        
2        NaN        NaN        NaN  129.210526  113.944000         NaN   
3  89.100000  88.766667        NaN  144.640000  108.400000  102.300000   
4  90.891111  91.600000  89.700000  143.000000  126.555556  100.332558   
5  91.600000  90.200000  93.300000  137.675000  136.720000   81.014286   
6  92.150000  91.451923  91.600000         NaN         NaN  109.700000   
8        NaN  91.700000        NaN         NaN         NaN         NaN   
9        NaN        NaN  89.116667         NaN         NaN         NaN   

                                                                           
x           4           5           6           7           8           9  
y                                                                          
2         NaN         NaN         NaN         NaN         NaN         NaN  
3  105.786364         NaN   88.476000   47.950000   83.500000         NaN  
4   92.927778  116.747826   89.866667  116.820000  273.800000   82.700000  
5  111.048000   34.200000   91.097959  111.827273  109.350000   49.500000  
6   50.900000  110.750000  133.933333  181.750000  133.919231  248.400000  
8         NaN         NaN         NaN         NaN  191.400000         NaN  
9         NaN         NaN         NaN         NaN         NaN   79.716667

## crosstab

In [317]:
pd.crosstab(df['month'],df['day'],margins=True)   #margins是边的意思

day    fri  mon  sat  sun  thu  tue  wed  All
month                                        
apr      1    1    1    3    2    0    1    9
aug     21   15   29   40   26   28   25  184
dec      1    4    0    1    1    1    1    9
feb      5    3    4    4    1    2    1   20
jan      0    0    1    1    0    0    0    2
jul      3    4    8    5    3    6    3   32
jun      3    3    2    4    2    0    3   17
mar     11   12   10    7    5    5    4   54
may      1    0    1    0    0    0    0    2
nov      0    0    0    0    0    1    0    1
oct      1    4    3    3    0    2    2   15
sep     38   28   25   27   21   19   14  172
All     85   74   84   95   61   64   54  517

# numpy

In [2]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
np.array(df)

array([[7, 5, 'mar', ..., 6.7, 0.0, 0.0],
       [7, 4, 'oct', ..., 0.9, 0.0, 0.0],
       [7, 4, 'oct', ..., 1.3, 0.0, 0.0],
       ..., 
       [7, 4, 'aug', ..., 6.7, 0.0, 11.16],
       [1, 4, 'aug', ..., 4.0, 0.0, 0.0],
       [6, 3, 'nov', ..., 4.5, 0.0, 0.0]], dtype=object)

## arange

In [332]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## linspace

In [9]:
np.linspace(1,100,num = 100)   #等份切割，等差数列

array([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
         10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,
         19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,
         37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,   45.,
         46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,   54.,
         55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,
         64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,   72.,
         73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.,
         82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
         91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,  100.])

## np.ones

In [341]:
np.ones((10,2))  #10行2列

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

## np.eye

In [10]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [345]:
np.eye(10).shape

(10, 10)

## np.zeros

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

## random

In [374]:
np.random.randint(10,size=[3,4])  #3行4列，返回小于10的

array([[4, 9, 8, 0],
       [5, 7, 8, 5],
       [8, 2, 6, 1]])

In [377]:
np.random.random(10)

array([ 0.74520691,  0.06362235,  0.81356669,  0.2245145 ,  0.57329284,
        0.06760623,  0.44508802,  0.91715266,  0.69928066,  0.23071986])

In [12]:
a  = np.random.randint(10,size=(3,4))
b = np.random.randint(10,size=(3,4))

In [13]:
a

array([[6, 6, 7, 0],
       [0, 8, 8, 2],
       [0, 8, 0, 8]])

In [14]:
b

array([[9, 8, 8, 1],
       [2, 0, 0, 5],
       [7, 2, 4, 3]])

## concatenate

In [386]:
np.concatenate((a,b),axis= 0)

array([[2, 6, 8, 3],
       [3, 3, 6, 3],
       [6, 6, 3, 9],
       [5, 1, 6, 8],
       [5, 1, 5, 3],
       [3, 5, 9, 6]])

## sum

In [18]:
np.sum(a,axis = 0)

array([ 6, 22, 15, 10])

In [19]:
np.sum(a,axis = 1)

array([19, 18, 16])

In [17]:
np.sum(a)

53

In [395]:
df.sum(axis = 0)

x                                                     2414
y                                                     2223
month    maroctoctmarmaraugaugaugsepsepsepsepaugsepseps...
day      frituesatfrisunsunmonmontuesatsatsatfrimonwedf...
FFMC                                               46863.3
DMC                                                  57321
DC                                                  283285
ISI                                                 4664.2
temp                                                9765.7
RH                                                   22897
wind                                                2077.1
rain                                                  11.2
area                                               6642.05
xx                                                    7051
label    SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...
dtype: object

## numpy索引切片

In [20]:
c = np.random.rand(20)

In [22]:
c

array([ 0.64433792,  0.21987085,  0.04993376,  0.70728044,  0.5308132 ,
        0.70186369,  0.61804809,  0.12107003,  0.82931234,  0.70623118,
        0.5522488 ,  0.03601092,  0.34809637,  0.00324196,  0.21266346,
        0.047187  ,  0.50677049,  0.89403646,  0.40136645,  0.62747643])

## 花式索引

In [41]:
f = np.eye(6)

In [42]:
f

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [43]:
f[(0,1,2,3,4),(1,2,3,4,5)]

array([ 0.,  0.,  0.,  0.,  0.])

In [47]:
mask = np.array([1,0,1,0,0,1],dtype=bool)

In [48]:
f[mask,0]

array([ 1.,  0.,  0.])

In [49]:
c[1:10:2]

array([ 0.21987085,  0.70728044,  0.70186369,  0.12107003,  0.70623118])

In [411]:
a= [1,2,3,4]

In [412]:
b = a

In [415]:
id(a)

2289797866312

In [413]:
id(a) == id(b)

True

In [404]:
b

[1, 2, 3, 4]

In [416]:
a.append(10)

In [419]:
id(a)

2289797866312

In [407]:
b

[1, 2, 3, 4, 10]

In [408]:
id(a)

2289797866888

In [410]:
id(b)

2289797866888