```
@refer: 《像Excel一样使用python进行数据分析》
Created on 2018-08-22
```

In [1]:
import pandas as pd
import numpy as np

# 创建数据表

依次填充日期

In [2]:
df = pd.DataFrame({"id":[1001,1002,1003,1004,1005,1006],
                  "date":pd.date_range('20130102',periods = 6),     
                  "city":['Beijing ','SH',' guangzhou','Shenzhen',
                         'shanghai','BEIJING '],
                  "age":[23,44,54,32,34,32],
                  "category":['100-A','100-B','110-A','110-C',
                             '210-A','130-F'],
                  "price":[1200,np.nan,2133,5433,np.nan,4432]},
                 columns=['id','date','city','category','age','price'])

In [3]:
df

id       date        city category  age   price
0  1001 2013-01-02    Beijing     100-A   23  1200.0
1  1002 2013-01-03          SH    100-B   44     NaN
2  1003 2013-01-04   guangzhou    110-A   54  2133.0
3  1004 2013-01-05    Shenzhen    110-C   32  5433.0
4  1005 2013-01-06    shanghai    210-A   34     NaN
5  1006 2013-01-07    BEIJING     130-F   32  4432.0

# 数据表检查

## 数据维度（行列）

In [4]:
df.shape

(6, 6)

## 数据表信息

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
id          6 non-null int64
date        6 non-null datetime64[ns]
city        6 non-null object
category    6 non-null object
age         6 non-null int64
price       4 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 368.0+ bytes


## 查看数据格式

一次性查看数据表中所有数据的格式，也可以指定一列来单独查看

In [38]:
df.dtypes 

id                   int64
date        datetime64[ns]
city                object
category            object
age                  int64
price              float64
dtype: object

In [39]:
df['age'].dtypes

dtype('int64')

## 查看空值

In [40]:
df.isnull()

id   date   city  category    age  price
0  False  False  False     False  False  False
1  False  False  False     False  False   True
2  False  False  False     False  False  False
3  False  False  False     False  False  False
4  False  False  False     False  False   True
5  False  False  False     False  False  False

In [41]:
df['price'].isnull()

0    False
1     True
2    False
3    False
4     True
5    False
Name: price, dtype: bool

## 查看唯一值

In [42]:
df['city'].unique()

array(['Beijing ', 'SH', ' guangzhou', 'Shenzhen', 'shanghai', 'BEIJING '], dtype=object)

## 查看数据表数值

In [43]:
df.values

array([[1001, Timestamp('2013-01-02 00:00:00'), 'Beijing ', '100-A', 23,
        1200.0],
       [1002, Timestamp('2013-01-03 00:00:00'), 'SH', '100-B', 44, nan],
       [1003, Timestamp('2013-01-04 00:00:00'), ' guangzhou', '110-A', 54,
        2133.0],
       [1004, Timestamp('2013-01-05 00:00:00'), 'Shenzhen', '110-C', 32,
        5433.0],
       [1005, Timestamp('2013-01-06 00:00:00'), 'shanghai', '210-A', 34,
        nan],
       [1006, Timestamp('2013-01-07 00:00:00'), 'BEIJING ', '130-F', 32,
        4432.0]], dtype=object)

In [6]:
df['price'].values

array([ 1200.,    nan,  2133.,  5433.,    nan,  4432.])

## 查看列名称

In [44]:
df.columns

Index(['id', 'date', 'city', 'category', 'age', 'price'], dtype='object')

## 查看前几行数据

In [45]:
df.head(3)

id       date        city category  age   price
0  1001 2013-01-02    Beijing     100-A   23  1200.0
1  1002 2013-01-03          SH    100-B   44     NaN
2  1003 2013-01-04   guangzhou    110-A   54  2133.0

## 查看后几行数据

In [46]:
df.tail(3)

id       date      city category  age   price
3  1004 2013-01-05  Shenzhen    110-C   32  5433.0
4  1005 2013-01-06  shanghai    210-A   34     NaN
5  1006 2013-01-07  BEIJING     130-F   32  4432.0

# 数据表清洗

## 处理空值（删除或填充）

```
DataFrame.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)[source]
any是只要有空值的行或列就删除，all是所有值均为空值的时候才删除
```

In [47]:
df.dropna(how = 'any') #删除数据表中含有空值的行

id       date        city category  age   price
0  1001 2013-01-02    Beijing     100-A   23  1200.0
2  1003 2013-01-04   guangzhou    110-A   54  2133.0
3  1004 2013-01-05    Shenzhen    110-C   32  5433.0
5  1006 2013-01-07    BEIJING     130-F   32  4432.0

In [48]:
df.fillna(value = 0) 

id       date        city category  age   price
0  1001 2013-01-02    Beijing     100-A   23  1200.0
1  1002 2013-01-03          SH    100-B   44     0.0
2  1003 2013-01-04   guangzhou    110-A   54  2133.0
3  1004 2013-01-05    Shenzhen    110-C   32  5433.0
4  1005 2013-01-06    shanghai    210-A   34     0.0
5  1006 2013-01-07    BEIJING     130-F   32  4432.0

In [49]:
df['price'].fillna(df['price'].mean(),inplace = True)

In [50]:
df

id       date        city category  age   price
0  1001 2013-01-02    Beijing     100-A   23  1200.0
1  1002 2013-01-03          SH    100-B   44  3299.5
2  1003 2013-01-04   guangzhou    110-A   54  2133.0
3  1004 2013-01-05    Shenzhen    110-C   32  5433.0
4  1005 2013-01-06    shanghai    210-A   34  3299.5
5  1006 2013-01-07    BEIJING     130-F   32  4432.0

## 清理空格

In [51]:
df['city'] = df['city'].map(str.strip)

In [52]:
df.values

array([[1001, Timestamp('2013-01-02 00:00:00'), 'Beijing', '100-A', 23,
        1200.0],
       [1002, Timestamp('2013-01-03 00:00:00'), 'SH', '100-B', 44, 3299.5],
       [1003, Timestamp('2013-01-04 00:00:00'), 'guangzhou', '110-A', 54,
        2133.0],
       [1004, Timestamp('2013-01-05 00:00:00'), 'Shenzhen', '110-C', 32,
        5433.0],
       [1005, Timestamp('2013-01-06 00:00:00'), 'shanghai', '210-A', 34,
        3299.5],
       [1006, Timestamp('2013-01-07 00:00:00'), 'BEIJING', '130-F', 32,
        4432.0]], dtype=object)

## 大小写转换

In [53]:
df['city'] = df['city'].str.lower()
df

id       date       city category  age   price
0  1001 2013-01-02    beijing    100-A   23  1200.0
1  1002 2013-01-03         sh    100-B   44  3299.5
2  1003 2013-01-04  guangzhou    110-A   54  2133.0
3  1004 2013-01-05   shenzhen    110-C   32  5433.0
4  1005 2013-01-06   shanghai    210-A   34  3299.5
5  1006 2013-01-07    beijing    130-F   32  4432.0

## 更改数据格式

In [54]:
df['price'].astype('int')

0    1200
1    3299
2    2133
3    5433
4    3299
5    4432
Name: price, dtype: int32

In [55]:
df['price'].dtypes

dtype('float64')

## 更改列名称

In [56]:
df.rename(columns = {'category':'category-size'})

id       date       city category-size  age   price
0  1001 2013-01-02    beijing         100-A   23  1200.0
1  1002 2013-01-03         sh         100-B   44  3299.5
2  1003 2013-01-04  guangzhou         110-A   54  2133.0
3  1004 2013-01-05   shenzhen         110-C   32  5433.0
4  1005 2013-01-06   shanghai         210-A   34  3299.5
5  1006 2013-01-07    beijing         130-F   32  4432.0

## 删除重复值

In [57]:
df['city'].drop_duplicates()

0      beijing
1           sh
2    guangzhou
3     shenzhen
4     shanghai
Name: city, dtype: object

In [58]:
df['city'].drop_duplicates(keep = 'last')

1           sh
2    guangzhou
3     shenzhen
4     shanghai
5      beijing
Name: city, dtype: object

## 数值修改及替换

In [59]:
df['city'].replace('sh','shanghai')

0      beijing
1     shanghai
2    guangzhou
3     shenzhen
4     shanghai
5      beijing
Name: city, dtype: object

# 数据预处理

## 数据表合并

In [60]:
df1 = pd.DataFrame({"id":[1001,1002,1003,1004,1005,1006,1007,1008],
                   "gender":['male','female','male','female','male',
                            'female','male','female'],
                   "pay":['Y','N','Y','Y','N','Y','N','Y'],
                   "m-point":[10,12,20,40,40,40,30,20]})

In [61]:
df

id       date       city category  age   price
0  1001 2013-01-02    beijing    100-A   23  1200.0
1  1002 2013-01-03         sh    100-B   44  3299.5
2  1003 2013-01-04  guangzhou    110-A   54  2133.0
3  1004 2013-01-05   shenzhen    110-C   32  5433.0
4  1005 2013-01-06   shanghai    210-A   34  3299.5
5  1006 2013-01-07    beijing    130-F   32  4432.0

In [62]:
df1

gender    id  m-point pay
0    male  1001       10   Y
1  female  1002       12   N
2    male  1003       20   Y
3  female  1004       40   Y
4    male  1005       40   N
5  female  1006       40   Y
6    male  1007       30   N
7  female  1008       20   Y

In [63]:
df_inner = pd.merge(df,df1,how = 'inner')

In [64]:
df_inner

id       date       city category  age   price  gender  m-point pay
0  1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y
1  1002 2013-01-03         sh    100-B   44  3299.5  female       12   N
2  1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y
3  1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y
4  1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N
5  1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y

In [65]:
df_left = pd.merge(df,df1,how = 'left')
df_left

id       date       city category  age   price  gender  m-point pay
0  1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y
1  1002 2013-01-03         sh    100-B   44  3299.5  female       12   N
2  1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y
3  1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y
4  1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N
5  1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y

## 设置索引列

In [66]:
df_inner.set_index('id')

date       city category  age   price  gender  m-point pay
id                                                                   
1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y
1002 2013-01-03         sh    100-B   44  3299.5  female       12   N
1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y
1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y
1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N
1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y

## 排序（按索引、按数值）

In [67]:
df_inner.sort_values(by = 'age')

id       date       city category  age   price  gender  m-point pay
0  1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y
3  1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y
5  1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y
4  1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N
1  1002 2013-01-03         sh    100-B   44  3299.5  female       12   N
2  1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y

In [68]:
df_inner.sort_index()

id       date       city category  age   price  gender  m-point pay
0  1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y
1  1002 2013-01-03         sh    100-B   44  3299.5  female       12   N
2  1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y
3  1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y
4  1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N
5  1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y

## 数据分组

打标签

In [69]:
df_inner['group'] = np.where(df_inner['price'] >3000,'high','low')

In [70]:
df_inner

id       date       city category  age   price  gender  m-point pay group
0  1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y   low
1  1002 2013-01-03         sh    100-B   44  3299.5  female       12   N  high
2  1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y   low
3  1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y  high
4  1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N  high
5  1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y  high

In [71]:
df_inner.loc[(df_inner['city'] == 'beijing') & (df_inner['price'] >=4000),'sign'] = 1
df_inner

id       date       city category  age   price  gender  m-point pay  \
0  1001 2013-01-02    beijing    100-A   23  1200.0    male       10   Y   
1  1002 2013-01-03         sh    100-B   44  3299.5  female       12   N   
2  1003 2013-01-04  guangzhou    110-A   54  2133.0    male       20   Y   
3  1004 2013-01-05   shenzhen    110-C   32  5433.0  female       40   Y   
4  1005 2013-01-06   shanghai    210-A   34  3299.5    male       40   N   
5  1006 2013-01-07    beijing    130-F   32  4432.0  female       40   Y   

  group  sign  
0   low   NaN  
1  high   NaN  
2   low   NaN  
3  high   NaN  
4  high   NaN  
5  high   1.0

## 数据分列

### 法一

In [78]:
pd.DataFrame((x.split('-') for x in df_inner['category']),index = df_inner.index,columns = ['category','size'])

category size
0      100    A
1      100    B
2      110    A
3      110    C
4      210    A
5      130    F

### 法二

In [88]:
pd.DataFrame(df['category'].str.split("-",1).tolist(),columns = ['category','size'])

category size
0      100    A
1      100    B
2      110    A
3      110    C
4      210    A
5      130    F

### 法三

In [89]:
df['category'],df['size'] = df['category'].str.split("-",1).str
df

id       date       city category  age   price size
0  1001 2013-01-02    beijing      100   23  1200.0    A
1  1002 2013-01-03         sh      100   44  3299.5    B
2  1003 2013-01-04  guangzhou      110   54  2133.0    A
3  1004 2013-01-05   shenzhen      110   32  5433.0    C
4  1005 2013-01-06   shanghai      210   34  3299.5    A
5  1006 2013-01-07    beijing      130   32  4432.0    F

### 法四

In [8]:
df['category'].str.split("-")

0    [100, A]
1    [100, B]
2    [110, A]
3    [110, C]
4    [210, A]
5    [130, F]
Name: category, dtype: object

In [9]:
df['category'].str.split("-").tolist()

[['100', 'A'],
 ['100', 'B'],
 ['110', 'A'],
 ['110', 'C'],
 ['210', 'A'],
 ['130', 'F']]

In [10]:
zip(df['category'].str.split("-").tolist())

In [97]:
df['category'],df['size'] = zip(*df['category'].str.split("-").tolist())

In [98]:
df

id       date        city category  age   price size
0  1001 2013-01-02    Beijing       100   23  1200.0    A
1  1002 2013-01-03          SH      100   44     NaN    B
2  1003 2013-01-04   guangzhou      110   54  2133.0    A
3  1004 2013-01-05    Shenzhen      110   32  5433.0    C
4  1005 2013-01-06    shanghai      210   34     NaN    A
5  1006 2013-01-07    BEIJING       130   32  4432.0    F